# SPDX-License-Identifier: AGPL-3.0-only
"""Hairstyle catalog: 10 styles, each {front, side, rear}.

Grids use the ``h/i/j`` hair slots (hl/mid/sh) so every style works with
every colour. Side views face LEFT. Head box x=8..23, skull top y6.
Front grids are intentionally allowed to be asymmetric (e.g. side_part),
so hair is NOT subject to the front-symmetry check.
"""
from engine import layer

# --- colour palettes ------------------------------------------------------
HAIR_BROWN = {'h': '#9e4539', 'i': '#6b3a26', 'j': '#3f2417'}
HAIR_BLOND = {'h': '#f9c22b', 'i': '#f79617', 'j': '#cd683d'}
HAIR_BLACK = {'h': '#45293f', 'i': '#2e222f', 'j': '#1a1420'}
HAIR_RED = {'h': '#e8834a', 'i': '#c25128', 'j': '#7a2f18'}
HAIR_GREY = {'h': '#d4cdc8', 'i': '#9a8f8a', 'j': '#665d58'}

HAIR_COLORS = {
    'braun': HAIR_BROWN,
    'blond': HAIR_BLOND,
    'schwarz': HAIR_BLACK,
    'rot': HAIR_RED,
    'grau': HAIR_GREY,
}

# --- MESSY — tousled short with volume, jagged fringe ---------------------
MESSY = {
    'front': layer({
        3:  (12, 'OOOOOOOO'),
        4:  (10, 'OOhhiiiiiiOO'),
        5:  (9,  'OhhhiiiiiiiiiO'),
        6:  (8,  'OhhhhiiiiiiiiiiO'),
        7:  (8,  'OhhhiiiiiiiiiijO'),
        8:  (8,  'OhhiiiiiiiiiiijO'),
        9:  (8,  'OiiijiiijiiiijjO'),
        10: (8,  'Oij..jj..jj..jjO'),
        11: (8,  'Ojj..........jjO'),
        12: (8,  'OO............OO'),
    }),
    'side': layer({
        3:  (13, 'OOOOOOO'),
        4:  (11, 'OOhhiiiiOO'),
        5:  (10, 'OhhhiiiiiiiO'),
        6:  (9,  'OhhhiiiiiiiiiO'),
        7:  (8,  'OhhhiiiiiiiiiiiO'),
        8:  (8,  'OhhiiiiiiiiiiijO'),
        9:  (8,  'Oij.iiiiiiiiijjO'),
        10: (13, 'OiiiiijjjO'),
        11: (14, 'OiiijjjjO'),
        12: (15, 'OjjjjjjO'),
        13: (17, 'OjjjO'),
    }),
    'rear': layer({
        3:  (12, 'OOOOOOOO'),
        4:  (10, 'OOhhiiiiiiOO'),
        5:  (9,  'OhhhiiiiiiiiiO'),
        6:  (8,  'OhhhhiiiiiiiiiiO'),
        7:  (8,  'OhhhiiiiiiiiiijO'),
        8:  (8,  'OhhiiiiiiiiiiijO'),
        9:  (8,  'OhiiiiiiiiiiiijO'),
        10: (8,  'OiiiiiiiiiiiiijO'),
        11: (8,  'OiiiiiiiiiiiijjO'),
        12: (8,  'OjiijiiijiijjjjO'),
        13: (8,  'Oj..j.jj.j..jjjO'),
    }),
}

# --- BOB — volume on top, sides framing the face down to the jaw ----------
BOB = {
    'front': layer({
        3:  (12, 'OOOOOOOO'),
        4:  (10, 'OOhhiiiiiiOO'),
        5:  (9,  'OhhhiiiiiiiiiO'),
        6:  (8,  'OhhhhiiiiiiiiiiO'),
        7:  (8,  'OhhhiiiiiiiiiijO'),
        8:  (8,  'OhhiiiiiiiiiiijO'),
        9:  (8,  'OhiiijiiiijiijjO'),
        10: (8,  'Oiii........jjjO'),
        11: (8,  'Oii..........jjO'),
        12: (8,  'Oii..........jjO'),
        13: (8,  'Oij..........jjO'),
        14: (8,  'Oij..........jjO'),
        15: (8,  'OjjO........OjjO'),
        16: (9,  'Oj..........jO'),
    }),
    'side': layer({
        3:  (13, 'OOOOOOO'),
        4:  (11, 'OOhhiiiiOO'),
        5:  (10, 'OhhhiiiiiiiO'),
        6:  (9,  'OhhhiiiiiiiiiO'),
        7:  (8,  'OhhhiiiiiiiiiiiO'),
        8:  (8,  'OhhiiiiiiiiiiijO'),
        9:  (8,  'OiiiiiiiiiiiijjO'),
        10: (13, 'OiiiiijjjO'),
        11: (13, 'OiiiiijjjO'),
        12: (13, 'OiiiijjjjO'),
        13: (13, 'OjiiijjjjO'),
        14: (13, 'OjjjjjjjjO'),
        15: (14, 'OOOOOOOO'),
    }),
    'rear': layer({
        3:  (12, 'OOOOOOOO'),
        4:  (10, 'OOhhiiiiiiOO'),
        5:  (9,  'OhhhiiiiiiiiiO'),
        6:  (8,  'OhhhhiiiiiiiiiiO'),
        7:  (8,  'OhhhiiiiiiiiiijO'),
        8:  (8,  'OhhiiiiiiiiiiijO'),
        9:  (8,  'OhiiiiiiiiiiiijO'),
        10: (8,  'OiiiiiiiiiiiiijO'),
        11: (8,  'OiiiiiiiiiiiiijO'),
        12: (8,  'OiiiiiiiiiiiijjO'),
        13: (8,  'OiiiiiiiiiiiijjO'),
        14: (8,  'OjiiiiiiiiiijjjO'),
        15: (8,  'OOjjjjjjjjjjjOO'),
        16: (9,  'OOOOOOOOOOOOO'),
    }),
}

# --- BUZZ — cropped close to the skull, low hairline ----------------------
BUZZ = {
    'front': layer({
        6:  (11, 'OOOOOOOOOO'),
        7:  (10, 'OjiiiiiiiijO'),
        8:  (9,  'OjiiiiiiiiiijO'),
        9:  (9,  'Oj..........jO'),
    }),
    'side': layer({
        6:  (11, 'OOOOOOOOOO'),
        7:  (10, 'OjiiiiiiiijO'),
        8:  (9,  'OjiiiiiiiiiijO'),
        9:  (13, 'jiiiiiiijO'),
        10: (16, 'jiiiijO'),
        11: (17, 'jiiijO'),
        12: (18, 'OjjjO'),
    }),
    'rear': layer({
        6:  (11, 'OOOOOOOOOO'),
        7:  (10, 'OjiiiiiiiijO'),
        8:  (9,  'OjiiiiiiiiiijO'),
        9:  (9,  'OiiiiiiiiiiiiO'),
        10: (9,  'OiiiiiiiiiiiiO'),
        11: (10, 'jiiiiiiiiiij'),
        12: (11, 'jjiiiiiijj'),
        13: (12, 'jjjjjjjj'),
    }),
}

# --- SIDE_PART — combed, parting line on the left (asymmetric) ------------
SIDE_PART = {
    'front': layer({
        3:  (12, 'OOOOOOOO'),
        4:  (10, 'OOhjiiiiiiOO'),
        5:  (9,  'OhhjiiiiiiiiiO'),
        6:  (8,  'OhhhjiiiiiiiiiiO'),
        7:  (8,  'OhhjiiiiiiiiiijO'),
        8:  (8,  'OhjiiiiiiiiiiijO'),
        9:  (8,  'Oij...iiiiiijjjO'),
        10: (8,  'Oj...........jjO'),
        11: (8,  'OO............OO'),
    }),
    'side': layer({
        3:  (13, 'OOOOOOO'),
        4:  (11, 'OOhhiiiiOO'),
        5:  (10, 'OhhhiiiiiiiO'),
        6:  (9,  'OhhiiiiiiiiiiO'),
        7:  (8,  'OhhiiiiiiiiiiijO'),
        8:  (8,  'OhiiiiiiiiiiiijO'),
        9:  (8,  'Oij.iiiiiiiiijjO'),
        10: (13, 'OiiiiijjjO'),
        11: (14, 'OiiijjjjO'),
        12: (15, 'OjjjjjjO'),
        13: (17, 'OjjjO'),
    }),
    'rear': layer({
        3:  (12, 'OOOOOOOO'),
        4:  (10, 'OOhhiiiiiiOO'),
        5:  (9,  'OhhhiiiiiiiiiO'),
        6:  (8,  'OhhhhiiiiiiiiiiO'),
        7:  (8,  'OhhhiiiiiiiiiijO'),
        8:  (8,  'OhhiiiiiiiiiiijO'),
        9:  (8,  'OhiiiiiiiiiiiijO'),
        10: (8,  'OiiiiiiiiiiiiijO'),
        11: (8,  'OjiiiiiiiiiiijjO'),
        12: (9,  'jiiiiiiiiiiijj'),
        13: (9,  'jjjjjjjjjjjjjj'),
    }),
}

# --- CURLY — bumpy silhouette, speckled texture ---------------------------
CURLY = {
    'front': layer({
        2:  (12, 'OO.OO..OO'),
        3:  (11, 'OOOOOOOOOO'),
        4:  (9,  'OOhihiiihiiiOO'),
        5:  (8,  'OOhihiiihiihiiOO'),
        6:  (7,  'OOhiihijiihiijiOO'),
        7:  (7,  'OOiijiihiijiiijOO'),
        8:  (7,  'OOijiiijiiihiijOO'),
        9:  (7,  'OOjiijiiijiiijjOO'),
        10: (7,  'OOj..jj..jj..jjOO'),
        11: (8,  'Ojj..........jjO'),
        12: (8,  'OO............OO'),
    }),
    'side': layer({
        2:  (13, 'OO.OO.O'),
        3:  (12, 'OOOOOOOO'),
        4:  (10, 'OOhihiiihOO'),
        5:  (9,  'OhihiiihiiihO'),
        6:  (8,  'OOhiihiijihiijOO'),
        7:  (7,  'OOhijiihiijiiijOO'),
        8:  (7,  'OOijiiijiihiijjOO'),
        9:  (8,  'Oij.iijhiiijjjjO'),
        10: (13, 'jiihiijjjO'),
        11: (13, 'jiiijiijjO'),
        12: (14, 'Ojjijjjjj'),
        13: (16, 'Ojjjjjj'),
        14: (18, 'OjjjO'),
    }),
    'rear': layer({
        2:  (12, 'OO.OO..OO'),
        3:  (11, 'OOOOOOOOOO'),
        4:  (9,  'OOhihiiihiiiOO'),
        5:  (8,  'OOhihiiihiihiiOO'),
        6:  (7,  'OOhiihijiihiijiOO'),
        7:  (7,  'OOiijiihiijiiijOO'),
        8:  (7,  'OOijiiijiiihiijOO'),
        9:  (7,  'OOjiijiiijiiijjOO'),
        10: (7,  'OOjiijiiijiiijjOO'),
        11: (8,  'OjiijiiijiiijjjO'),
        12: (9,  'jjiijjjijjjjjj'),
        13: (10, 'jj.jjj.jj.jj'),
    }),
}

# --- SPIKY — spikes on top ------------------------------------------------
SPIKY = {
    'front': layer({
        1:  (12, 'O..O..O..O'),
        2:  (11, 'OhOOiOOiOOjO'),
        3:  (10, 'OhhOiiOiiOjjO'),
        4:  (9,  'OhhhiiiiiiijjO'),
        5:  (9,  'OhhiiiiiiiiijO'),
        6:  (8,  'OhhiiiiiiiiiiijO'),
        7:  (8,  'OhiiiiiiiiiiiijO'),
        8:  (8,  'OiiiiiiiiiiiiijO'),
        9:  (8,  'Oij..ji..ij..jjO'),
        10: (8,  'Ojj..........jjO'),
        11: (8,  'OO............OO'),
    }),
    'side': layer({
        1:  (13, 'O..O..O'),
        2:  (12, 'OhOOiOOjO'),
        3:  (11, 'OhhOiiOjjO'),
        4:  (10, 'OhhiiiiiiiijO'),
        5:  (9,  'OhiiiiiiiiiiijO'),
        6:  (8,  'OhiiiiiiiiiiiijO'),
        7:  (8,  'OhiiiiiiiiiiiijO'),
        8:  (8,  'OiiiiiiiiiiiiijO'),
        9:  (8,  'Oij.iiiiiiiiijjO'),
        10: (13, 'OiiiiijjjO'),
        11: (14, 'OiiijjjjO'),
        12: (15, 'OjjjjjjO'),
        13: (17, 'OjjjO'),
    }),
    'rear': layer({
        1:  (12, 'O..O..O..O'),
        2:  (11, 'OhOOiOOiOOjO'),
        3:  (10, 'OhhOiiOiiOjjO'),
        4:  (9,  'OhhhiiiiiiijjO'),
        5:  (9,  'OhhiiiiiiiiijO'),
        6:  (8,  'OhhiiiiiiiiiiijO'),
        7:  (8,  'OhiiiiiiiiiiiijO'),
        8:  (8,  'OiiiiiiiiiiiijjO'),
        9:  (8,  'OjiiiiiiiiiiijjO'),
        10: (9,  'jiiiiiiiiiijj'),
        11: (11, 'jj.jj.jj.j'),
    }),
}

# --- LONG — open, falling past the shoulders ------------------------------
LONG = {
    'front': layer({
        3:  (12, 'OOOOOOOO'),
        4:  (10, 'OOhhiiiiiiOO'),
        5:  (9,  'OhhhiiiiiiiiiO'),
        6:  (8,  'OhhhhiiiiiiiiiiO'),
        7:  (8,  'OhhhiiiiiiiiiijO'),
        8:  (8,  'OhhiiiiiiiiiiijO'),
        9:  (8,  'OhiiijiiiijiijjO'),
        10: (8,  'Oiii........jjjO'),
        11: (8,  'Oiii........jjjO'),
        12: (8,  'Oiii........jjjO'),
        13: (8,  'Oiii........jjjO'),
        14: (8,  'Oiii........jjjO'),
        15: (8,  'Oiii........jjjO'),
        16: (8,  'Oiii........jjjO'),
        17: (8,  'Ojii........jjjO'),
        18: (8,  'Ojii........jjjO'),
        19: (8,  'OjjjO......OjjjO'),
        20: (8,  'OO............OO'),
    }),
    'side': layer({
        3:  (13, 'OOOOOOO'),
        4:  (11, 'OOhhiiiiOO'),
        5:  (10, 'OhhhiiiiiiiO'),
        6:  (9,  'OhhiiiiiiiiiiO'),
        7:  (8,  'OhhiiiiiiiiiiijO'),
        8:  (8,  'OhiiiiiiiiiiiijO'),
        9:  (8,  'Oij.iiiiiiiiijjO'),
        10: (12, 'OiiiiiijjjjO'),
        11: (12, 'OiiiiiijjjjO'),
        12: (12, 'OiiiiiijjjjO'),
        13: (12, 'OiiiiiijjjjO'),
        14: (12, 'OiiiiiijjjjO'),
        15: (12, 'OiiiiiijjjjO'),
        16: (12, 'OiiiiiijjjjO'),
        17: (12, 'OjiiiiijjjjO'),
        18: (13, 'OiiiiijjjjO'),
        19: (14, 'OjjjjjjjjO'),
        20: (15, 'OOOOOOOOO'),
    }),
    'rear': layer({
        3:  (12, 'OOOOOOOO'),
        4:  (10, 'OOhhiiiiiiOO'),
        5:  (9,  'OhhhiiiiiiiiiO'),
        6:  (8,  'OhhhhiiiiiiiiiiO'),
        7:  (8,  'OhhhiiiiiiiiiijO'),
        8:  (8,  'OhhiiiiiiiiiiijO'),
        9:  (8,  'OiiijiiiijiiijjO'),
        10: (8,  'OiiijiiiijiiijjO'),
        11: (8,  'OiiijiiiijiiijjO'),
        12: (8,  'OiiijiiiijiiijjO'),
        13: (8,  'OiiijiiiijiiijjO'),
        14: (8,  'OiiijiiiijiiijjO'),
        15: (8,  'OiiijiiiijiiijjO'),
        16: (8,  'OiiijiiiijiiijjO'),
        17: (8,  'OjiijiiiijiiijjO'),
        18: (8,  'OjiijiiiijiiijjO'),
        19: (9,  'OjjiijjiijjjjO'),
        20: (10, 'OOOOOOOOOOOO'),
    }),
}

# --- PONYTAIL — tight cap, tail swinging behind ---------------------------
PONYTAIL = {
    'front': layer({
        4:  (11, 'OOOOOOOOOO'),
        5:  (10, 'OhhiiiiiiiiO'),
        6:  (9,  'OhhiiiiiiiiiiO'),
        7:  (8,  'OhhiiiiiiiiiiijO'),
        8:  (8,  'OhiiiiiiiiiiiijO'),
        9:  (8,  'Oii..........jjO'),
        10: (8,  'OO............OO'),
    }),
    'side': layer({
        4:  (12, 'OOOOOOOO'),
        5:  (10, 'OhhiiiiiiiiiO'),
        6:  (9,  'OhhiiiiiiiiiiO'),
        7:  (8,  'OhhiiiiiiiiiiijO'),
        8:  (8,  'OhiiiiiiiiiiiijO'),
        9:  (8,  'Oij.........jjjO'),
        10: (21, 'OiijO'),
        11: (22, 'OiijO'),
        12: (22, 'OiijO'),
        13: (23, 'OiijO'),
        14: (23, 'OjjO'),
        15: (24, 'OjO'),
    }),
    'rear': layer({
        4:  (11, 'OOOOOOOOOO'),
        5:  (10, 'OhhiiiiiiiiO'),
        6:  (9,  'OhhiiiiiiiiiiO'),
        7:  (8,  'OhhiiiiiiiiiiijO'),
        8:  (8,  'OhiiiiiiiiiiiijO'),
        9:  (8,  'OiiiiiijjiiiijjO'),
        10: (9,  'jiiiijjiijjiij'),
        11: (13, 'OiiijO'),
        12: (13, 'OiiijO'),
        13: (13, 'OjiijO'),
        14: (13, 'OjijO'),
        15: (14, 'OjjO'),
        16: (14, 'OjO'),
    }),
}

# --- BUN — tight cap with a knot on top -----------------------------------
BUN = {
    'front': layer({
        1:  (13, 'OOOOOO'),
        2:  (12, 'OhhiiiiO'),
        3:  (12, 'OjiiiijO'),
        4:  (11, 'OOOOOOOOOO'),
        5:  (10, 'OhhiiiiiiiiO'),
        6:  (9,  'OhhiiiiiiiiiiO'),
        7:  (8,  'OhhiiiiiiiiiiijO'),
        8:  (8,  'OhiiiiiiiiiiiijO'),
        9:  (8,  'Oii..........jjO'),
        10: (8,  'OO............OO'),
    }),
    'side': layer({
        1:  (16, 'OOOOO'),
        2:  (15, 'OhiiijO'),
        3:  (15, 'OjiiijO'),
        4:  (12, 'OOOOOOOO'),
        5:  (10, 'OhhiiiiiiiiiO'),
        6:  (9,  'OhhiiiiiiiiiiO'),
        7:  (8,  'OhhiiiiiiiiiiijO'),
        8:  (8,  'OhiiiiiiiiiiiijO'),
        9:  (8,  'Oij.........jjjO'),
        10: (18, 'jiijO'),
        11: (19, 'OjjO'),
    }),
    'rear': layer({
        1:  (13, 'OOOOOO'),
        2:  (12, 'OhhiiiiO'),
        3:  (12, 'OjiiiijO'),
        4:  (11, 'OOOOOOOOOO'),
        5:  (10, 'OhhiiiiiiiiO'),
        6:  (9,  'OhhiiiiiiiiiiO'),
        7:  (8,  'OhhiiiijjiiiiijO'),
        8:  (8,  'OhiiiijiijiiiijO'),
        9:  (8,  'OiiiijiiiijiiijO'),
        10: (9,  'jiiijiiiijiiij'),
        11: (10, 'jiijiiiijiij'),
        12: (11, 'jjjjjjjjjj'),
    }),
}

# --- BALD — no hair at all (bare skull); empty in every view --------------
# Exposes the "no hairstyle" option so the base outfit can read as truly bare.
# Empty grids draw nothing and are NOT subject to the front-symmetry check.
BALD = {
    'front': [],
    'side': [],
    'rear': [],
}

# --- BRAIDS — middle parting, two braids hanging in front -----------------
BRAIDS = {
    'front': layer({
        4:  (11, 'OOOOOOOOOO'),
        5:  (10, 'OhiiiijiiiiO'),
        6:  (8,  'OhhiiiijiiiiiiiO'),
        7:  (8,  'OhiiiiijiiiiiiiO'),
        8:  (8,  'OiiiiiijiiiiiijO'),
        9:  (8,  'Oij..........jiO'),
        10: (8,  'OiiO........OiiO'),
        11: (8,  'OjjO........OjjO'),
        12: (8,  'OiiO........OiiO'),
        13: (8,  'OjjO........OjjO'),
        14: (8,  'OiiO........OiiO'),
        15: (8,  'OjjO........OjjO'),
        16: (8,  'OjO..........OjO'),
        17: (8,  'OO............OO'),
    }),
    'side': layer({
        4:  (12, 'OOOOOOOO'),
        5:  (10, 'OhhiiiiiiiiiO'),
        6:  (9,  'OhhiiiiiiiiiiO'),
        7:  (8,  'OhhiiiiiiiiiiijO'),
        8:  (8,  'OhiiiiiiiiiiiijO'),
        9:  (8,  'Oii.........jjjO'),
        10: (8,  'OiiO.....OjjjO'),
        11: (8,  'OjjO......OjjO'),
        12: (8,  'OiiO'),
        13: (8,  'OjjO'),
        14: (8,  'OiiO'),
        15: (8,  'OjjO'),
        16: (8,  'OjO'),
        17: (8,  'OO'),
    }),
    'rear': layer({
        4:  (11, 'OOOOOOOOOO'),
        5:  (10, 'OhiiiijiiiiO'),
        6:  (8,  'OhhiiiijiiiiiiiO'),
        7:  (8,  'OhiiiiijiiiiiiiO'),
        8:  (8,  'OiiiiiijiiiiiijO'),
        9:  (8,  'OiiiiiijiiiiiijO'),
        10: (8,  'OiiOiiijiiiOiiO'),
        11: (8,  'OjjOjiiiiijOjjO'),
        12: (8,  'OiiOOjjjjjOOiiO'),
        13: (8,  'OjjO........OjjO'),
        14: (8,  'OiiO........OiiO'),
        15: (8,  'OjjO........OjjO'),
        16: (8,  'OjO..........OjO'),
        17: (8,  'OO............OO'),
    }),
}

HAIRSTYLES = {
    'messy': MESSY,
    'bob': BOB,
    'buzz': BUZZ,
    'side_part': SIDE_PART,
    'curly': CURLY,
    'spiky': SPIKY,
    'long': LONG,
    'ponytail': PONYTAIL,
    'bun': BUN,
    'braids': BRAIDS,
    'bald': BALD,
}
