import React from 'react';

export const styles: Record<string, React.CSSProperties> = {
  overlay: {
    position: 'fixed',
    inset: 0,
    background: 'rgba(0,0,0,0.6)',
    backdropFilter: 'blur(4px)',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    zIndex: 9999,
  },
  modal: {
    background: 'var(--glass, rgba(30,30,30,0.95))',
    borderRadius: 16,
    border: '1px solid var(--border, rgba(255,255,255,0.1))',
    width: '90%',
    maxWidth: 600,
    maxHeight: '85vh',
    display: 'flex',
    flexDirection: 'column',
    overflow: 'hidden',
  },
  header: {
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
    padding: '16px 20px',
    borderBottom: '1px solid var(--border, rgba(255,255,255,0.1))',
  },
  title: {
    margin: 0,
    fontSize: 18,
    fontWeight: 600,
    color: 'var(--fg, #fff)',
  },
  closeBtn: {
    background: 'none',
    border: 'none',
    fontSize: 24,
    cursor: 'pointer',
    color: 'var(--fg-subtle, #888)',
    padding: 0,
    lineHeight: 1,
  },
  tabs: {
    display: 'flex',
    gap: 4,
    padding: '8px 16px',
    borderBottom: '1px solid var(--border, rgba(255,255,255,0.1))',
  },
  tab: {
    padding: '8px 16px',
    background: 'transparent',
    border: 'none',
    borderRadius: 8,
    cursor: 'pointer',
    color: 'var(--fg-subtle, #888)',
    fontSize: 14,
    fontWeight: 500,
  },
  tabActive: {
    background: 'var(--accent, #3b82f6)',
    color: '#fff',
  },
  content: {
    padding: 20,
    overflowY: 'auto',
    flex: 1,
  },
  loading: {
    padding: 40,
    textAlign: 'center',
    color: 'var(--fg-subtle, #888)',
  },
  error: {
    padding: 20,
    color: '#ef4444',
    textAlign: 'center',
  },
  card: {
    background: 'rgba(255,255,255,0.05)',
    borderRadius: 12,
    padding: 16,
    marginBottom: 16,
  },
  cardTitle: {
    margin: '0 0 12px',
    fontSize: 14,
    fontWeight: 600,
    color: 'var(--fg-subtle, #888)',
    textTransform: 'uppercase',
    letterSpacing: '0.5px',
  },
  planInfo: {
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  planName: {
    fontSize: 24,
    fontWeight: 700,
    color: 'var(--fg, #fff)',
  },
  planPrice: {
    fontSize: 18,
    color: 'var(--fg-subtle, #888)',
  },
  cancelNotice: {
    marginTop: 12,
    padding: '8px 12px',
    background: 'rgba(239,68,68,0.15)',
    borderRadius: 8,
    color: '#ef4444',
    fontSize: 13,
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  periodInfo: {
    marginTop: 8,
    fontSize: 13,
    color: 'var(--fg-subtle, #888)',
  },
  usageInfo: {},
  usageNumbers: {
    marginBottom: 8,
  },
  usageCurrent: {
    fontSize: 32,
    fontWeight: 700,
    color: 'var(--fg, #fff)',
  },
  usageLimit: {
    fontSize: 16,
    color: 'var(--fg-subtle, #888)',
    marginLeft: 4,
  },
  usageBar: {
    height: 8,
    background: 'rgba(255,255,255,0.1)',
    borderRadius: 4,
    overflow: 'hidden',
  },
  usageFill: {
    height: '100%',
    borderRadius: 4,
    transition: 'width 0.3s ease',
  },
  usageLabel: {
    marginTop: 8,
    fontSize: 12,
    color: 'var(--fg-subtle, #888)',
  },
  actions: {
    display: 'flex',
    gap: 12,
    marginTop: 8,
  },
  primaryBtn: {
    flex: 1,
    padding: '12px 20px',
    background: 'var(--accent, #3b82f6)',
    border: 'none',
    borderRadius: 8,
    color: '#fff',
    fontSize: 14,
    fontWeight: 600,
    cursor: 'pointer',
  },
  dangerBtn: {
    flex: 1,
    padding: '12px 20px',
    background: 'transparent',
    border: '1px solid #ef4444',
    borderRadius: 8,
    color: '#ef4444',
    fontSize: 14,
    fontWeight: 600,
    cursor: 'pointer',
  },
  linkBtn: {
    background: 'none',
    border: 'none',
    color: 'var(--accent, #3b82f6)',
    cursor: 'pointer',
    fontSize: 13,
    textDecoration: 'underline',
    marginLeft: 8,
  },
  invoiceList: {
    display: 'flex',
    flexDirection: 'column',
    gap: 8,
  },
  invoiceItem: {
    display: 'flex',
    alignItems: 'center',
    padding: 12,
    background: 'rgba(255,255,255,0.05)',
    borderRadius: 8,
    gap: 12,
  },
  invoiceMain: {
    flex: 1,
  },
  invoiceNumber: {
    fontWeight: 600,
    color: 'var(--fg, #fff)',
    fontSize: 14,
  },
  invoiceDate: {
    fontSize: 12,
    color: 'var(--fg-subtle, #888)',
  },
  invoiceRight: {
    textAlign: 'right',
  },
  invoiceAmount: {
    fontWeight: 600,
    color: 'var(--fg, #fff)',
  },
  invoiceStatus: {
    fontSize: 12,
    textTransform: 'uppercase',
  },
  invoiceActions: {
    display: 'flex',
    gap: 8,
  },
  invoiceLink: {
    color: 'var(--accent, #3b82f6)',
    textDecoration: 'none',
    fontSize: 13,
  },
  emptyState: {
    padding: 40,
    textAlign: 'center',
    color: 'var(--fg-subtle, #888)',
  },
  plansList: {
    display: 'grid',
    gap: 12,
  },
  planCard: {
    padding: 16,
    background: 'rgba(255,255,255,0.05)',
    borderRadius: 12,
    border: '1px solid transparent',
  },
  planCardCurrent: {
    border: '1px solid var(--accent, #3b82f6)',
  },
  planCardHeader: {
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 8,
  },
  planCardName: {
    fontSize: 18,
    fontWeight: 600,
    color: 'var(--fg, #fff)',
  },
  planCardPrice: {
    fontSize: 16,
    fontWeight: 600,
    color: 'var(--accent, #3b82f6)',
  },
  planCardDesc: {
    fontSize: 13,
    color: 'var(--fg-subtle, #888)',
    marginBottom: 8,
  },
  planCardLimit: {
    fontSize: 14,
    color: 'var(--fg, #fff)',
    marginBottom: 12,
  },
  planFeatures: {
    margin: '0 0 12px',
    paddingLeft: 20,
    fontSize: 13,
    color: 'var(--fg-subtle, #888)',
  },
  planFeature: {
    marginBottom: 4,
  },
  planBtn: {
    width: '100%',
    padding: '10px 16px',
    background: 'var(--accent, #3b82f6)',
    border: 'none',
    borderRadius: 8,
    color: '#fff',
    fontSize: 14,
    fontWeight: 600,
    cursor: 'pointer',
  },
  planBtnCurrent: {
    background: 'rgba(255,255,255,0.1)',
    color: 'var(--fg-subtle, #888)',
    cursor: 'default',
  },
};
