#!/usr/bin/env node
/**
 * Compose the Prisma schema used at build/runtime.
 *
 * Inputs:
 *   apps/server/prisma/schema.prisma                          (OSS base, source of truth)
 *   <enterpriseRoot>/prisma/schema.enterprise.prisma          (optional fragment)
 *
 * Output:
 *   apps/server/prisma/schema.composed.prisma                 (gitignored)
 *
 * The enterprise fragment lives in a separate closed-source repo
 * (meetropolis-enterprise). Its location is resolved in this order — the
 * first candidate whose fragment file exists wins:
 *   1. MEETROPOLIS_ENTERPRISE_PATH env var (absolute or repo-root-relative)
 *   2. Sibling-clone default: ../meetropolis-enterprise (parallel to the OSS repo)
 *   3. In-tree default: <REPO_ROOT>/packages/tenancy-enterprise (used by the
 *      Docker build context, where prepare-build.sh rsyncs sibling sources
 *      into packages/tenancy-enterprise/ so the build sees them)
 *   4. None of the above: OSS-only mode (fragment ignored, base copied verbatim)
 *
 * Behaviour:
 *   - Without the enterprise fragment: copies the OSS base verbatim.
 *   - With the fragment: splices the marked field-blocks into the matching
 *     OSS models (Tenant, AssetPack, AvatarPack), then appends the fragment's
 *     enums and standalone models.
 *
 * Idempotent. Safe to run on every prisma invocation.
 */

const fs = require('node:fs');
const path = require('node:path');

const SCRIPT_DIR = __dirname;
const REPO_ROOT = path.resolve(SCRIPT_DIR, '..', '..', '..');

function resolveFragmentPath() {
  const candidates = [];
  const envValue = process.env.MEETROPOLIS_ENTERPRISE_PATH;
  if (envValue && envValue.trim().length > 0) {
    candidates.push(path.isAbsolute(envValue) ? envValue : path.resolve(REPO_ROOT, envValue));
  }
  // Sibling clone parallel to the OSS repo (Tiamat-maintainer local setup).
  candidates.push(path.resolve(REPO_ROOT, '..', 'meetropolis-enterprise'));
  // In-tree location used by the Docker build context: prepare-build.sh
  // rsyncs the sibling sources into packages/tenancy-enterprise/.
  candidates.push(path.resolve(REPO_ROOT, 'packages', 'tenancy-enterprise'));

  for (const root of candidates) {
    const fragment = path.join(root, 'prisma', 'schema.enterprise.prisma');
    if (fs.existsSync(fragment)) return { root, fragment };
  }
  return { root: candidates[0], fragment: path.join(candidates[0], 'prisma', 'schema.enterprise.prisma') };
}

const { fragment: FRAGMENT } = resolveFragmentPath();
const OSS_SCHEMA = path.join(SCRIPT_DIR, 'schema.prisma');
const OUTPUT = path.join(SCRIPT_DIR, 'schema.composed.prisma');

const HEADER =
  '// AUTO-GENERATED by apps/server/prisma/compose-schema.cjs — do not edit.\n' +
  '// Source: schema.prisma (+ <MEETROPOLIS_ENTERPRISE_PATH>/prisma/schema.enterprise.prisma if present)\n\n';

function fail(msg) {
  console.error('[compose-schema] ' + msg);
  process.exit(1);
}

function readBase() {
  if (!fs.existsSync(OSS_SCHEMA)) fail('OSS base schema missing: ' + OSS_SCHEMA);
  return fs.readFileSync(OSS_SCHEMA, 'utf8');
}

function readFragment() {
  if (!fs.existsSync(FRAGMENT)) return null;
  return fs.readFileSync(FRAGMENT, 'utf8');
}

/**
 * Extracts a marker block from the fragment and uncomments its body lines.
 * Each body line starts with `// ` — that prefix is stripped on extraction.
 */
function extractFieldBlock(fragment, name) {
  const begin = '// __' + name + '_BEGIN__';
  const end = '// __' + name + '_END__';
  const startIdx = fragment.indexOf(begin);
  const endIdx = fragment.indexOf(end, startIdx);
  if (startIdx === -1 || endIdx === -1) return null;
  const body = fragment.slice(startIdx + begin.length, endIdx);
  return body
    .split('\n')
    .map((line) => line.replace(/^\s*\/\/\s?/, ''))
    .filter((line) => line.trim().length > 0)
    .join('\n');
}

/**
 * Strips all marker block sections (BEGIN…END including the markers) from a
 * fragment string so they don't appear as comments in the composed output.
 */
function stripFieldBlocks(fragment) {
  return fragment.replace(/\/\/ __[A-Z_]+_BEGIN__[\s\S]*?\/\/ __[A-Z_]+_END__\n?/g, '');
}

/**
 * Splices a block of field lines into the body of `model <ModelName> { ... }`
 * inside the base schema text. The lines are indented to match the model body
 * (2 spaces) and inserted just before the closing brace, separated by a blank
 * line for readability.
 */
function spliceFieldsIntoModel(base, modelName, fieldsBlock) {
  if (!fieldsBlock) return base;
  const re = new RegExp('(model\\s+' + modelName + '\\s*\\{)([\\s\\S]*?)(\\n\\})', 'm');
  if (!re.test(base)) fail('cannot find `model ' + modelName + '` in OSS base schema');
  const indented = fieldsBlock
    .split('\n')
    .map((line) => (line.length > 0 ? '  ' + line : line))
    .join('\n');
  // Function form of String.replace avoids `$` substitutions in the body.
  return base.replace(re, (_match, open, body, close) => {
    return open + body + '\n  // --- enterprise fields (composed) ---\n' + indented + close;
  });
}

function main() {
  const base = readBase();
  const fragment = readFragment();

  if (!fragment) {
    fs.writeFileSync(OUTPUT, HEADER + base, 'utf8');
    console.log(
      '[compose-schema] wrote ' + path.relative(REPO_ROOT, OUTPUT) + ' (OSS-only mode, no enterprise fragment)',
    );
    return;
  }

  const tenantFields = extractFieldBlock(fragment, 'TENANT_ENTERPRISE_FIELDS');
  const assetPackFields = extractFieldBlock(fragment, 'ASSETPACK_ENTERPRISE_FIELDS');
  const avatarPackFields = extractFieldBlock(fragment, 'AVATARPACK_ENTERPRISE_FIELDS');

  let composed = base;
  composed = spliceFieldsIntoModel(composed, 'Tenant', tenantFields);
  composed = spliceFieldsIntoModel(composed, 'AssetPack', assetPackFields);
  composed = spliceFieldsIntoModel(composed, 'AvatarPack', avatarPackFields);

  const fragmentBody = stripFieldBlocks(fragment).trim();
  composed =
    composed.trimEnd() +
    '\n\n// =============================================================================\n' +
    '// Enterprise extension (composed from ' +
    path.relative(REPO_ROOT, FRAGMENT) +
    ')\n' +
    '// =============================================================================\n\n' +
    fragmentBody +
    '\n';

  fs.writeFileSync(OUTPUT, HEADER + composed, 'utf8');
  console.log(
    '[compose-schema] wrote ' +
      path.relative(REPO_ROOT, OUTPUT) +
      ' (full mode, enterprise fragment merged from ' +
      path.relative(REPO_ROOT, FRAGMENT) +
      ')',
  );
}

main();
